# fly.toml app configuration file generated for laravel-nuxt-template-frontend on 2025-05-06T14:42:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# 注意: このファイルを使用する前に、app名を任意のユニークな名前に変更してください

app = 'your-app-name-frontend'  # ← ユニークなアプリ名に変更してください
primary_region = 'nrt'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
