name: Deploy to Fly.io (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for Fly.io API Token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -z "$FLY_API_TOKEN" ]; then
            echo "❌ FLY_API_TOKEN secret is not set"
            echo "Please add your Fly.io API token to repository secrets:"
            echo "1. Go to your repository Settings > Secrets and variables > Actions"
            echo "2. Add a new secret named 'FLY_API_TOKEN'"
            echo "3. Set the value to your Fly.io API token (get it from: flyctl auth token)"
            exit 1
          fi
          echo "✅ FLY_API_TOKEN is configured"

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Deploy Frontend
        working-directory: ./frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
