AWSTemplateFormatVersion: "2010-09-09"
Description: "GitHub Actions Role for CI/CD Pipelines"

Parameters:
  GitHubOrg:
    Type: String
    Description: "GitHub Organization name"
  GitHubRepo:
    Type: String
    Description: "GitHub Repository name (or * for all repositories in the organization)"
    Default: "*"
  OIDCProviderArn:
    Type: String
    Description: "ARN of the GitHub OIDC Provider (if already exists)"
    Default: ""

Conditions:
  CreateOIDCProvider:
    Fn::Equals:
      - !Ref OIDCProviderArn
      - ""

Resources:
  # GitHub OIDC Provider (条件付きで作成)
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"

  # GitHub Actions用ロール
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "github-actions-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: 
                Fn::If:
                  - CreateOIDCProvider
                  - !GetAtt GitHubOIDCProvider.Arn
                  - !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      ManagedPolicyArns:
        - !Ref GitHubActionsPolicy

  # GitHub Actions用ポリシー
  GitHubActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "github-actions-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # ECRリポジトリ操作権限
          - Effect: Allow
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - ecr:GetAuthorizationToken
            Resource: "*"
          # ECSサービス操作権限
          - Effect: Allow
            Action:
              - ecs:UpdateService
              - ecs:DescribeServices
              - ecs:RegisterTaskDefinition
              - ecs:DescribeTaskDefinition
            Resource: "*"
          # IAMロール参照権限
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"
            Condition:
              StringEquals:
                "iam:PassedToService": "ecs-tasks.amazonaws.com"
          # CloudWatchログ操作権限
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:log-group:/aws/ecs/*"

Outputs:
  GitHubActionsRoleArn:
    Description: "ARN of the GitHub Actions Role"
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: "github-actions-role-arn"
  
  OIDCProviderArn:
    Description: "ARN of the GitHub OIDC Provider"
    Value: 
      Fn::If:
        - CreateOIDCProvider
        - !GetAtt GitHubOIDCProvider.Arn
        - !Ref OIDCProviderArn
    Export:
      Name: "github-oidc-provider-arn"
