AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure Deployer Role for IaC operations

Resources:
  InfrastructureDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: infrastructure-deployer
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              # 必要に応じて個人IAMや組織のIAMユーザー/ロールARNを追加
              AWS: "490468214947"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        # 必要に応じて他のサービスも追加
      Path: /
      Description: Role for deploying infrastructure via CloudFormation, ECS, etc.

Outputs:
  InfrastructureDeployerRoleArn:
    Value: !GetAtt InfrastructureDeployerRole.Arn
    Description: ARN of the infrastructure-deployer role
