AWSTemplateFormatVersion: "2010-09-09"
Description: "Book Management System - RDS PostgreSQL Infrastructure"

Parameters:
  ProjectName:
    Type: String
    Default: book-management
    Description: Name of the project

  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment type (production, staging, development)

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the database will be deployed

  DBSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first private subnet ID for the database

  DBSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second private subnet ID for the database

  DBName:
    Type: String
    Default: book_management
    Description: The name of the database

  DBUsername:
    Type: String
    Default: dbadmin
    Description: The master username for the database
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters

  DBPassword:
    Type: String
    NoEcho: true
    Description: The master password for the database
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.r5.large
      - db.r5.xlarge
    Description: The database instance type

  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 1000
    Description: The size of the database (GiB)

  DBBackupRetentionPeriod:
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35
    Description: The number of days to keep automated backups

Resources:
  # データベースサブネットグループ
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${ProjectName}-${Environment} database subnet group
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-subnet-group

  # データベースセキュリティグループ
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ProjectName}-${Environment} RDS security group
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          Description: Allow PostgreSQL connections
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-sg

  # データベースパラメータグループ
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub ${ProjectName}-${Environment} PostgreSQL parameter group
      Family: postgres17
      Parameters:
        shared_buffers: 32768
        max_connections: 100
        log_statement: "ddl"
        log_min_duration_statement: 1000
        autovacuum: 1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-param-group

  # PostgreSQL データベースインスタンス
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-db
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: 16.8
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      DBParameterGroupName: !Ref DBParameterGroup
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      PreferredBackupWindow: 01:00-02:00
      PreferredMaintenanceWindow: sun:03:00-sun:04:00
      CopyTagsToSnapshot: true
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      DeletionProtection: true
      PubliclyAccessible: false
      Port: 5432
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db

Outputs:
  DBEndpoint:
    Description: PostgreSQL database endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-endpoint

  DBPort:
    Description: PostgreSQL database port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-port

  DBName:
    Description: PostgreSQL database name
    Value: !Ref DBName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-name

  DBSecurityGroupId:
    Description: Security group ID for the database
    Value: !GetAtt DBSecurityGroup.GroupId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-sg-id
